// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fliawfhbwcuozghbqocp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaWF3Zmhid2N1b3pnaGJxb2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjQ5NDcsImV4cCI6MjA2MzkwMDk0N30.d4fk4zMhaEQukA_h0IkkVRdwkrpdnyAl4ZRTIO0-5Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);